### ISSUE TITLE
Hello, how would this work on a B450M DS3H by Gigabyte?

### ISSUE THREAD

**Issue by Croat233** [bakedpotato191/ryzentosh#2]
Should it go without issues just like its MSI counterpart, what do you think?

**Comment by superrnovae** [comment]
Hello! Our mobos are different, so you have to change some stuff.

 - Generate your own SSDTs with the help of SSDTTime
 - Specify correct PciPaths under DeviceProperties in config.plist
 - Either remove USBMap.kext or create your own after you've installed macOS. (if some ports aren't working ofc or you're experiencing sleep issues)

Also, don't forget to [generate](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial) SMBIOS values.

**Comment by Croat233** [comment]
> Hello! Our mobos are different, so you have to change some stuff.
> 
> * Generate your own SSDTs with the help of SSDTTime
> * Specify correct PciPaths under DeviceProperties in config.plist
> * Either remove USBMap.kext or create your own after you've installed macOS. (if some ports aren't working ofc or you're experiencing sleep issues)
> 
> Also, don't forget to [generate](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial) SMBIOS values.

Yeah, I should better wait for someone with my mobo who's more experienced instead :)

**Comment by superrnovae** [comment]
> > Hello! Our mobos are different, so you have to change some stuff.
> 
> > 
> 
> > * Generate your own SSDTs with the help of SSDTTime
> 
> > * Specify correct PciPaths under DeviceProperties in config.plist
> 
> > * Either remove USBMap.kext or create your own after you've installed macOS. (if some ports aren't working ofc or you're experiencing sleep issues)
> 
> > 
> 
> > Also, don't forget to [generate](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial) SMBIOS values.
> 
> 
> 
> Yeah, I should better wait for someone with my mobo who's more experienced instead :)

It's not that hard. Dortania's guide explains everything in detail and step by step.
